backend:
  name: git-gateway
  branch: main # Or your main branch name (e.g., master)

media_folder: "src/images" # Where your images will be stored
public_folder: "/images" # The public path to your images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Human friendly name
    folder: "src/blog" # The path to your blog post Markdown files
    create: true # Allows users to create new blog posts
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }